<?php

namespace Warriors\AdminBundle\Entity;

/**
 * SubmenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubmenuRepository extends \Doctrine\ORM\EntityRepository
{
}
