Warriors\AdminBundle\Entity\Usuarios:
    type: entity
    table: null
    repositoryClass: Warriors\AdminBundle\Entity\UsuariosRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '100'
        password:
            type: string
            length: '100'
    lifecycleCallbacks: {  }
